<a href="https://colab.research.google.com/github/rani-sikdar/Tensorflow-Learning/blob/main/Tensorflow_keras_MNIST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.17.1


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [5]:
# Build a machine learning model

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [7]:
predictions = model(x_train[:1]).numpy()

predictions

array([[ 0.72106147,  0.4403255 , -0.31205583, -0.5807395 ,  0.38910702,
         0.8679965 ,  0.15256596, -0.0903521 , -0.11624824,  0.4841452 ]],
      dtype=float32)

In [8]:
# The tf.nn.softmax function converts these logits to probabilities for each class:

tf.nn.softmax(predictions).numpy()

array([[0.15404756, 0.116341  , 0.05482489, 0.04190732, 0.11053222,
        0.17843002, 0.08724899, 0.06843249, 0.06668311, 0.12155236]],
      dtype=float32)

In [9]:
# Define a loss function for training

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [10]:
loss_fn(y_train[:1], predictions).numpy()

1.7235588

In [11]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [13]:
# Train and evaluate your model

model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9695 - loss: 0.1022
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9743 - loss: 0.0835
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9795 - loss: 0.0661
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9816 - loss: 0.0598
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9826 - loss: 0.0523


In [14]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9795 - loss: 0.0718


[0.07178697735071182, 0.9794999957084656]

In [15]:
# If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:

probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [17]:

probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.0899053e-08, 5.3188624e-11, 2.2378144e-07, 1.2645106e-04,
        2.7994667e-11, 7.1844544e-09, 1.2166150e-14, 9.9987066e-01,
        4.3314255e-08, 2.6008699e-06],
       [4.6254257e-08, 2.6020665e-05, 9.9994290e-01, 3.1118911e-05,
        1.2402766e-18, 1.0797532e-08, 6.9009332e-10, 2.7968626e-14,
        1.9166180e-08, 2.1823853e-15],
       [6.9713855e-07, 9.9855834e-01, 1.3133200e-04, 5.6788067e-06,
        4.5105313e-05, 2.2140696e-06, 6.4262226e-06, 7.0075842e-04,
        5.4719322e-04, 2.1465987e-06],
       [9.9978429e-01, 2.6976565e-08, 1.2828450e-04, 8.1908200e-07,
        1.3272452e-06, 9.8154169e-06, 1.6934409e-06, 4.4278968e-05,
        3.4432421e-08, 2.9416287e-05],
       [1.6474874e-07, 1.2835356e-09, 1.4986481e-06, 1.2639332e-08,
        9.9954295e-01, 1.1551881e-07, 3.2339202e-08, 1.9656720e-04,
        1.4180154e-07, 2.5860185e-04]], dtype=float32)>